# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true 
cache: packages
branches:
    only:
        - master
        - dev
matrix:
    include:
        - os: linux
          r: release
          before_deploy: Rscript -e 'install.packages("pkgdown")'
          deploy:
            provider: script
            script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
            skip_cleanup: true
            on: 
                all_branches: true
        - os: linux
          r: oldrel 
        - os: linux
          r: devel
        - os: osx
          r: release
        - os: osx
          r: oldrel
r_packages:
    - covr
    - igraph
    - testthat
after_success:
    - Rscript -e 'covr::codecov()'
